version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:13.5.0
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: yarn install
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Execute Jest
          command: yarn test
      - run:
          name: Code coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          destination: tests
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_test_results:
          path: test-results.xml
